from typing import List, Dict, Any
from .base import SecurityCheck
import json

class ConfigurationAuditCheck(SecurityCheck):
    def run_check(self, dataset: Dict[str, Any]) -> List[Dict[str, Any]]:
        findings = []
        
        # Dynamically audit news_channels.json or news_channels_x.json
        if "news_channels" in dataset:
            x_data = dataset["news_channels"]
            if "channels" in x_data and "full" in x_data["channels"]:
                for idx, channel in enumerate(x_data["channels"]["full"]):
                    # Flag Tier 1 channels that don't have an accountId verified
                    if channel.get("tier") == 1 and not channel.get("accountId"):
                        findings.append({
                            "title": f"Missing Account ID Verification for Tier-1 Feed: @{channel.get('handle', 'unknown')}",
                            "category": "Configuration / Trust",
                            "severity": "Medium",
                            "cvss": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N (4.3)",
                            "confidence": "High",
                            "affected_component": f"OSINT Aggregator Config (index {idx})",
                            "description": f"The Tier-1 news channel @{channel.get('handle')} is missing a verified numeric 'accountId'. Unverified handles silently degrade the feed and are vulnerable to identity forking if a handle is renamed.",
                            "impact": "An attacker could claim a dropped handle and inject disinformation directly into the Tier-1 intelligence feed, leading to false alerts being generated by the system.",
                            "remediation": "Enforce strict schema validation on the configuration file. Ensure all enabled accounts (especially Tier-1) require a numeric 'accountId' verified against the platform API.",
                            "status": "Confirmed",
                            "evidence": [
                                {
                                    "evidence_type": "Config Snippet",
                                    "description": "Channel object missing accountId.",
                                    "raw_data": json.dumps(channel, indent=2)
                                }
                            ]
                        })
        return findings
